proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true

applications:
- name: guardrails--toxic_language
  route_prefix: /validator/guardrails/toxic_language
  import_path: app_ray_serve:app
  runtime_env: {
    "pip": ["fastapi", "transformers", "torch", "torchvision", "detoxify"],
    "working_dir": "https://github.com/guardrails-ai/toxic_language/archive/f208ad6aad6c4011a0e519de354e4a0f57b0c169.zip",
    "env_vars": {
      "env": "prod"
    }
  }
  deployments:
  - name: InferenceDeployment
    num_replicas: 1
    ray_actor_options:
      num_cpus: 1.0
      num_gpus: 1.0
    user_config:
      version: 15
  - name: Ingress
    num_replicas: 1
    ray_actor_options:
      num_cpus: 2.0
      num_gpus: 0.0
    user_config:
      version: 15
