proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true

applications:
- name: guardrails--toxic_language
  route_prefix: /guardrails/toxic_language
  import_path: app_ray_serve:app
  runtime_env: {
    "pip": ["fastapi", "transformers", "torch", "torchvision", "detoxify"],
    "working_dir": "https://github.com/guardrails-ai/toxic_language/archive/f208ad6aad6c4011a0e519de354e4a0f57b0c169.zip"
  }
  deployments:
  - name: InferenceDeployment
    num_replicas: 1
    user_config:
      version: 14
  - name: Ingress
    user_config:
      version: 14