proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true

applications:
- name: guardrails--toxic_language
  route_prefix: /guardrails--toxic_language
  import_path: app_ray_serve:app
  runtime_env: {
    "pip": ["fastapi", "transformers", "torch", "torchvision", "detoxify"],
  }
  deployments:
  - name: AppModel
    num_replicas: 1
    user_config:
      version: 6
  - name: Ingress
    user_config:
      version: 6