name: Sagemaker ECR Publish (RC)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      is_release_candidate:
        description: 'Is this a release candidate?'
        required: true
        default: 'true'

# Needed for OIDC / assume role
permissions:
  id-token: write  
  contents: read    

jobs:
  publish_image:
    name: Publish Sagemaker Image (Release Candidate)
    runs-on: ubuntu-latest
    env:
      VALIDATOR_TAG_NAME: toxiclanguage
      AWS_REGION: us-east-1
      WORKING_DIR: "./"
      AWS_CI_ROLE__PROD: ${{ secrets.AWS_CI_ROLE__PROD }}
      AWS_ECR_RELEASE_CANDIDATE: ${{ inputs.is_release_candidate || 'true' }}
    steps: 
    
      - name: Check out head
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set ECR Tag
        id: set-ecr-tag
        run: |
          if [ ${{ env.AWS_ECR_RELEASE_CANDIDATE }} == 'true' ]; then
            echo "This is a release candidate."
            echo "Setting tag to -rc"
            ECR_TAG=$VALIDATOR_TAG_NAME-rc
          else
            echo "This is a production image."
            ECR_TAG=$VALIDATOR_TAG_NAME
          fi
          echo "Setting ECR tag to $ECR_TAG"
          echo "ECR_TAG=$ECR_TAG" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          platforms: linux/amd64

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_CI_ROLE__PROD}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build & Push ECR Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ env.WORKING_DIR }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: 064852979926.dkr.ecr.us-east-1.amazonaws.com/gr-sagemaker-validator-images-prod:${{ steps.set-ecr-tag.outputs.ECR_TAG }}
